### ISSUE TITLE
Processing xls or txt `file_type`s in the getSeriesObservations endpoint

### ISSUE THREAD

**Issue by Hunter-Github** [Rleahy22/fredApi#2]
Right now, the code thinks the response is only xml or json. Things break subtly once `file_type: 'xls'` is selected.

**Comment by Rleahy22** [comment]
The Fred API [docs](http://api.stlouisfed.org/docs/fred/category.html) say that requests can return either xml or json.  Since they do not say they support xls, I did not implement it.
